JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/Chronos.java, JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/ChronosURLProvider.java, JobProxyModel/pom.xml, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/JobProxyInterface.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/framework/URLProvider.java, JobProxyServer/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServer.java
=> zookeeper framework configuration added

README.md
=> developer guide

JobProxyChronos/pom.xml, JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/Chronos.java, JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/data/ChronosJob.java, JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/data/ChronosJobState.java, JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/data/ChronosState.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/State.java, JobProxyServer/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServer.java, doc/REST/paths.md, doc/REST/swagger.yaml
=> get job states

JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/Ping.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/State.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/Submit.java, doc/REST/overview.md, doc/REST/swagger.yaml
=>  add REST api version 

JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/Chronos.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/Delete.java, JobProxyServer/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServer.java, doc/REST/paths.md, doc/REST/swagger.yaml
=> delete chronos endpoint + documentation 

JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/State.java
=> remove human readable endpoints

JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/State.java, doc/REST/swagger.yaml
=> state using GET instead of POST

JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/Chronos.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/JobProxyInterface.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/exceptions/FrameworkException.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/Delete.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/State.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/Submit.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/task/TContainer.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/task/TMounts.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/task/Task.java, JobProxyServer/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServer.java, pom.xml
=> Basic error handling

JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/Chronos.java, JobProxyJavaDocker/pom.xml, JobProxyJavaDocker/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/javadocker/JavaDocker.java, JobProxyJavaDocker/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/javadocker/JavaDockerURLProvider.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/JobProxyInterface.java, JobProxyServer/pom.xml, JobProxyServer/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServer.java, README.md, pom.xml
=> java docker integration added

JobProxyModel/pom.xml, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/DummyFramework.java, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/JerseyMethodTest.java, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/model/Misc.java, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/DeleteTest.java, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/PingTest.java, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/StateTest.java, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/SubmitTest.java, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/model/task/ContainerTest.java, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/model/task/MountTest.java, JobProxyModel/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/model/task/TaskTest.java
=> model based tests

JobProxyModel/pom.xml, JobProxyServer/pom.xml, JobProxyServer/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServerTest.java
=> server based tests added

JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/Chronos.java, JobProxyChronos/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/chronos/ChronosURLProvider.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/JobProxyFactory.java, JobProxyServer/pom.xml, JobProxyServer/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServer.java, JobProxyServer/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServerTest.java, JobProxyServerCLI/nbactions.xml, JobProxyServerCLI/pom.xml, JobProxyServerCLI/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/CLI.java, JobProxyServerCLI/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/Result.java, JobProxyServerCLI/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/SystemResult.java, JobProxyServerCLI/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/CLISteps.java, JobProxyServerCLI/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/CLIStories.java, JobProxyServerCLI/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/ExampleFramework.java, JobProxyServerCLI/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/VariableResult.java, JobProxyServerCLI/src/test/resources/CLI.story, pom.xml
=> behave tests

circle.yml
=>  continuous integration 

JobProxyLocal/pom.xml, JobProxyModel/pom.xml, JobProxyServer/pom.xml, JobProxyServerCLI/pom.xml, pom.xml
=> maven enforcer

JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/rest/Delete.java
=> remove consumes annotation

README.md
=> fix developer section for importing artifacts

JobProxyLocal/pom.xml, JobProxyModel/pom.xml, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/JobProxyFactory.java, JobProxyServer/pom.xml, JobProxyServer/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServer.java, JobProxyServer/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/server/JobProxyServerTest.java, JobProxyServerCLI/pom.xml, JobProxyServerCLI/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/CLI.java, JobProxyServerCLI/src/test/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/CLISteps.java, JobProxyServerCLI/src/test/resources/CLI.story
-log <loggerlevel> parameter added  see #70
=> logger level added 

JobProxyJavaDocker/pom.xml, JobProxyJavaDocker/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/javadocker/JavaDocker.java, JobProxyServer/pom.xml, JobProxyServerCLI/pom.xml, pom.xml
=> fix JavaDockerMounts

JobProxyLocal/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/local/Local.java, JobProxyModel/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/model/JobProxyFactory.java, JobProxyServerCLI/pom.xml, JobProxyServerCLI/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/server/cli/CLI.java
=> fix local docker

JobProxyLocal/pom.xml, JobProxyLocal/src/main/java/de/unibi/cebitec/bibiserv/jobproxy/local/Local.java
=> fix(JobProxyLocal): pull image before run
